const motors = [
    {
      id: 1,
      tipe: "Beat 2010",
      merek: "Honda",
      kategori: "Matic",
      transmisi: "Otomatis",
      kondisi: "Mulus, terawat dengan baik",
      kapasitas: "4 liter",
      cc: 110,
      kecepatan: "100 km/jam",
      deskripsi: "Motor matic irit bahan bakar dengan performa handal untuk aktivitas sehari-hari.",
      harga: "50000",
      status: "tersedia"
    },
    {
      id: 2,
      tipe: "Vario 150",
      merek: "Honda",
      kategori: "Matic",
      transmisi: "Otomatis",
      kondisi: "Mulus, seperti baru",
      kapasitas: "5,5 liter",
      cc: 150,
      kecepatan: "120 km/jam",
      deskripsi: "Desain modern dan elegan, cocok untuk perjalanan jarak jauh maupun dekat.",
      harga: "70000",
      status: "tersedia"
    },
    {
      id: 3,
      tipe: "Nmax 2020",
      merek: "Yamaha",
      kategori: "Matic",
      transmisi: "Otomatis",
      kondisi: "Mulus, terawat dengan baik",
      kapasitas: "7,1 liter",
      cc: 155,
      kecepatan: "130 km/jam",
      deskripsi: "Skutik premium dengan ruang kaki luas dan fitur canggih.",
      harga: "90000",
      status: "tersedia"
    },
    {
      id: 4,
      tipe: "Aerox 155",
      merek: "Yamaha",
      kategori: "Sport",
      transmisi: "Otomatis",
      kondisi: "Mulus, seperti baru",
      kapasitas: "5,5 liter",
      cc: 155,
      kecepatan: "125 km/jam",
      deskripsi: "Motor sport matic dengan performa tinggi dan desain sporty.",
      harga: "80000",
      status: "tersedia"
    },
    {
      id: 5,
      tipe: "PCX 2021",
      merek: "Honda",
      kategori: "Matic",
      transmisi: "Otomatis",
      kondisi: "Mulus, terawat dengan baik",
      kapasitas: "8 liter",
      cc: 160,
      kecepatan: "135 km/jam",
      deskripsi: "Motor matic kelas premium dengan kenyamanan ekstra.",
      harga: "100000",
      status: "tersedia"
    },
    {
      id: 6,
      tipe: "Primavera 2020",
      merek: "Vespa",
      kategori: "Classic",
      transmisi: "Otomatis",
      kondisi: "Mulus, seperti baru",
      kapasitas: "7 liter",
      cc: 150,
      kecepatan: "120 km/jam",
      deskripsi: "Desain klasik dengan teknologi modern dan irit bahan bakar.",
      harga: "120000",
      status: "dirental"
    },
    {
      id: 7,
      tipe: "KLX 150",
      merek: "Kawasaki",
      kategori: "Trail",
      transmisi: "Manual",
      kondisi: "Mulus, siap untuk segala medan",
      kapasitas: "6,9 liter",
      cc: 150,
      kecepatan: "110 km/jam",
      deskripsi: "Motor trail yang tangguh untuk segala medan.",
      harga: "80000",
      status: "dirental"
    },
    {
      id: 8,
      tipe: "XSR 155",
      merek: "Yamaha",
      kategori: "Retro",
      transmisi: "Manual",
      kondisi: "Mulus, seperti baru",
      kapasitas: "10 liter",
      cc: 155,
      kecepatan: "125 km/jam",
      deskripsi: "Motor retro-modern dengan gaya klasik dan performa tinggi.",
      harga: "100000",
      status: "dirental"
    },
    {
      id: 9,
      tipe: "CBR 250RR",
      merek: "Honda",
      kategori: "Sport",
      transmisi: "Manual",
      kondisi: "Mulus, terawat dengan baik",
      kapasitas: "12 liter",
      cc: 250,
      kecepatan: "160 km/jam",
      deskripsi: "Motor sport dengan performa maksimal, cocok untuk perjalanan jauh.",
      harga: "150000",
      status: "dirental"
    },
    {
      id: 10,
      tipe: "R15 V3",
      merek: "Yamaha",
      kategori: "Sport",
      transmisi: "Manual",
      kondisi: "Mulus, siap dipakai",
      kapasitas: "11 liter",
      cc: 155,
      kecepatan: "140 km/jam",
      deskripsi: "Motor sport dengan desain agresif dan performa tinggi.",
      harga: "120000",
      status: "dirental"
    }
  ];
  
  export default motors;
  