import type { Metadata } from "next";
import "./globals.css";
import { Montserrat,Bree_Serif } from 'next/font/google';
import { twMerge } from "tailwind-merge";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import Navbar from "@/components/Navbar";
const montserrat = Montserrat({
  subsets:['latin'],
  variable: "--font-sans",
})

const breeSerif = Bree_Serif({
  subsets: ['latin'],
  variable: "--font-serif",
  weight: ["400"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(montserrat.variable,breeSerif.variable,"font-sans antialiased bg-bgone text-primary")}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
